### ISSUE TITLE
netMHCpan_install.py can not download 'data' file for netMHCIIpan

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#111]
Expected Behavior:

> Download the working `data` folder for netMHCIIpan. Find the correct path for downloading this data.

Current Behavior:

> gzip: data.tar.gz: No such file or directory
> tar: data.tar: Cannot open: No such file or directory
> tar: Error is not recoverable: exiting now
> rm: cannot remove 'data.tar': No such file or directory
> (base) <username>@octarine:~/PANDORA$ wget https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.1/data.tar.gz
> --2022-02-02 12:12:19--  https://services.healthtech.dtu.dk/services/NetMHCIIpan-4.1/data.tar.gz
> Resolving services.healthtech.dtu.dk (services.healthtech.dtu.dk)... 192.38.87.75
> Connecting to services.healthtech.dtu.dk (services.healthtech.dtu.dk)|192.38.87.75|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2022-02-02 12:12:19 ERROR 404: Not Found.

Detailed Description:

> In https://services.healthtech.dtu.dk/service.php?NetMHCIIpan-4.1 there is no `data.tar.gz` file to be downloaded

**Comment by cbaakman** [comment]
I think it should also say that one would have to download some netMHCpan and netMHCIIpan files manually. The install script seems outdated and needs to be replaced.

**Comment by DarioMarzella** [comment]
NetMHCpan now needs to be installed by the user manually. PANDORA will not take care of its installation anymore.
