### ISSUE TITLE
MHCII wrapper running for benchmarking not successful 

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#122]
## Expected Behavior:

 Model all the cases listed in the .tsv file

## Current Behavior:
Error:

> WARNING: no anchor positions provided. Pandora will predict them using netMHCIIpan.
> Traceback (most recent call last):
>   File "run_all.py", line 12, in <module>
>     wrap.create_targets('/home/fmeiman/PANDORA/PANDORA_files/data/csv_pkl_files/benchmark.tsv', db, MHC_class='II', delimiter='\t', header="False", IDs_col=2, M_chain_col=3,N_chain_col=4,  benchmark=True)
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Wrapper/Wrapper.py", line 202, in create_targets
>     tar = PMHC.Target(target_id, allele_type=self.targets[target_id]['allele'],
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/PMHC/PMHC.py", line 261, in __init__
>     self.anchors = Modelling_functions.predict_anchors_netMHCIIpan(self.peptide, self.allele_type)
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Modelling_functions.py", line 197, in predict_anchors_netMHCIIpan
>     offset, core, core_reliability = max_scores[0]
> IndexError: list index out of range

## Detailed Description:
As an input the .tsv file format used is: 

` <peptide> <allele> <ID> <M_seq> <N_seq>` 

Seems the problem occurs while predicting anchor by NetMHCIIpan

**Comment by DarioMarzella** [comment]
I have seen this happening already when there was a problem with the netMHCIIpan installation. Can you check where it is installed? It should be in the PANDORA main folder, as "netMHCIIpan-4.0".
Inside, there should be a file called `netMHCIIpan`. 
Please check lines 14 and 15 of that file, where NMHOME (netmhcpan home) and TMPDIR (temp dir) are defined. Be sure those paths are correct.

**Comment by DarioMarzella** [comment]
@FarzanehParizi is this issue still permanent? Or should I close it? I had no issues with the Wrapper on MHCII since...
