### ISSUE TITLE
list cases with small molecules around the peptide 

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#143]
Expected Behavior:
>List cases with small molecules around the peptide flanking region to not be included for benchmarking

Current Behavior:
>Fine

Detailed Description:
>Randomly checking 7KEI, 4H25,1UVQ have small molecules around Flanking region
>Better to extract them and consider their flanking region RMSD does not make sense
> But be included in the template set, t=so that the conformation of the core still be used for modelling

**Comment by DarioMarzella** [comment]
Related to #144 , same solution: If most of the cases have one of these two issues, we mention it and simply report the full RMSD to be fair, but we say it's unreliable.
