### ISSUE TITLE
List cases with peptides having crystal packing contacts 

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#144]
Expected Behavior:

>List cases having crystal contact not to be included for part of benchmarking

Current Behavior:

>Fine

Detailed Description:

>To be omitted only for benchmarking especially whole peptide RMSD, but not be ommited from template set so the core can be used for modelling

**Comment by DarioMarzella** [comment]
Double-check if this is needed. We can also just report these is a high chance of this happening and not report the list, if almost every case has it.
