### ISSUE TITLE
Better check for probable errors in the beginning of a process

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#153]
Expected Behavior:
>When constructing the database, first checks the file if exists and then proceed. This is true for any other type of errors

Current Behavior:
>Fine

Detailed Description:
>When the address for the save Database is wrong, after many hours of retrieving PDBs from IMGT, then the database is not saved >in the end.
>This issue is mainly for consideration to check probable errors at the beginning of processes

**Comment by DarioMarzella** [comment]
Related to #156. 
@gcroci2 You can maybe keep this in mind while working on #156 and add a simple .isinstance check to prevent it from crashing later in the process.
