### ISSUE TITLE
The NonHuman_MHC_data.fasta does not exist in correct directory

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#154]
>Expected behaviour

The NonHuman_MHC_data.fasta be saved in correct folder

>Current behaviour

rm: cannot remove 'OLD_MHC_prot.fasta': No such file or directory
cat: /mnt/home1/fmeiman/PANDORA/PANDORA_files/data/csv_pkl_files/NonHuman_MHC_data.fasta: No such file or directory
Traceback (most recent call last):
  File "run_PANDORA_new_databse.py", line 8, in <module>
    db.construct_database(save='/home/fmeiman/PANDORA_files/data/csv_pkl_files/pandora_Database_20220724.pkl')
  File "/mnt/home1/fmeiman/PANDORA/PANDORA/Database/Database.py", line 112, in construct_database
    self.construct_both_blast_db(databases_data_dir)
  File "/mnt/home1/fmeiman/PANDORA/PANDORA/Database/Database.py", line 243, in construct_both_blast_db
    subprocess.check_call(command, shell=True)
  File "/home/fmeiman/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cat /mnt/home1/fmeiman/PANDORA/PANDORA_files/data/csv_pkl_files/Human_MHC_data.fasta /mnt/home1/fmeiman/PANDORA/PANDORA_files/data/csv_pkl_files/NonHuman_MHC_data.fasta > /mnt/home1/fmeiman/PANDORA/PANDORA_files/data/csv_pkl_files/refseq_blast_db/refseq_blast_db.fasta' returned non-zero exit status 1.

> Detailed description

After fetching the latest updates and constructing the database it is complaining about the  file does not exist in ./PANDORA_files/data/csv_pkl_files, but the file has been saved in ./PANDORA folder

**Comment by DarioMarzella** [comment]
Related to #156. Should be fixed when 156 is fixed.

**Comment by cbaakman** [comment]
I had the same problem, when using PANDORA_database from github, thus not the install script.

**Comment by gcroci2** [comment]
Is this fixed now? @DarioMarzella @FarzanehParizi

**Comment by DarioMarzella** [comment]
Yes, it is fixed in the development branch.
