### ISSUE TITLE
Wrap up database in a single folder

### ISSUE THREAD

**Issue by DarioMarzella** [X-lab-3D/PANDORA#156]
- [x] Wrap up database in a single, default folder (e.g. `PANDORA/database/default`).
- [x] Adapt all the default paths in the code to adhere to this change.

This should solve #86 #93 #142

**Comment by gcroci2** [comment]
Keep in mind [#153](https://github.com/X-lab-3D/PANDORA/issues/153)

**Comment by gcroci2** [comment]
Related to #154

**Comment by gcroci2** [comment]
[PANDORA_database repo](https://github.com/X-lab-3D/PANDORA_database/tree/main/data) should be reorganized as follows:

```
└── PANDORA_database
    └── default
         ├── PDBs/pMHCI
         └── csv_pkl_files
```
Is this right? @DarioMarzella

**Comment by DarioMarzella** [comment]
Yes, something like that. Maybe we can find some better names, suggestions are very welcome. something like:
```
└── Database
    └── default
         ├── logfile.txt           <-- The default logfile produced while generating the database, maybe with added date of the creation and options used (not crucial for this issue).
         ├── PDBs
               ├──  Bad / IMGT           <-- two separate folders used during the db generation, can be removed at the end of the process or kept (with a given option) for debugging reasons
               ├──  pMHCI   
               └──  pMHCII
         ├── blast_databases
         ├── <>.csv
         └── db.pkl               
       ```  
If I am not wrong, there are only two extra csv files (<>.csv) that contain the list of IDs downloaded from IMGT. They can also be removed at the end of the creation or kept only for debugging (via an option). In case there are other text files, we can do a folder for all of them (that would take the place of what now is csv_pkl_files).

Also, note that changing the structure of the folders might impact the default output directory of PANDORA (mentioned in #70 ).

**Comment by gcroci2** [comment]
> #70

Perfect, thanks. This seems pretty clear now! And about the need of rebasing paths? I am not getting why it is needed, and in case if we should solve it in this issue.

**Comment by gcroci2** [comment]
> Yes, something like that. Maybe we can find some better names, suggestions are very welcome. something like:
> 
> ```
> └── Database
>     └── default
>          ├── logfile.txt           <-- The default logfile produced while generating the database, maybe with added date of the creation and options used (not crucial for this issue).
>          ├── PDBs
>                ├──  Bad / IMGT           <-- two separate folders used during the db generation, can be removed at the end of the process or kept (with a given option) for debugging reasons
>                ├──  pMHCI   
>                └──  pMHCII
>          ├── blast_databases
>          ├── <>.csv
>          └── db.pkl               
> ```
> 
> If I am not wrong, there are only two extra csv files (<>.csv) that contain the list of IDs downloaded from IMGT. They can also be removed at the end of the creation or kept only for debugging (via an option). In case there are other text files, we can do a folder for all of them (that would take the place of what now is csv_pkl_files).
> 
> Also, note that changing the structure of the folders might impact the default output directory of PANDORA (mentioned in #70 ).

Perfect, thanks. This seems pretty clear now! And about the need of rebasing paths? I am not getting why it is needed, and in case if we should solve it in this issue.

**Comment by gcroci2** [comment]
Hi @DarioMarzella! I started working on it, and I have some questions:

```
└── Database
    └── default
         ├── logfile.txt
         ├── PDBs
               ├──  IMGT
               ├──  Bad Are pMHCI/ and pMHCII/ supposed to be in Bad/ (they are in the code) and are they different from the ones one level above?**
               ├──  pMHCI   
               └──  pMHCII
         ├── blast_databases **Where in the code is this generated?**
         ├── <>.csv **Are these the fasta files? If not, when are they generated in the code and how are they called?**
         └── db.pkl  
```
And also:
- Where do we want to put the fasta files (`Human_MHC_data.fasta` and `NonHuman_MHC_data.fasta`)? Only in `default/` or in a subfolder (`default/fasta/`)?
- `/PANDORA_files/data/PDBs/IMGT_retrieved/` should be moved to `/PANDORA_files/default/PDBs/IMGT/`, right?
- `csv_pkl_files` should be deleted, right?

**Comment by DarioMarzella** [comment]
Hi Giulia:
1) About the "Bad" folder: yes, it is better two keep two separate pMHCI and II folders inside for clarity reason.
2) For the blast database: called in [line 112 of Database.py](https://github.com/X-lab-3D/PANDORA/blob/547e3193eb61d694ff505f6706929f5aa628cda5/PANDORA/Database/Database.py#L112) (from the development branch), they are produced by [this function.](https://github.com/X-lab-3D/PANDORA/blob/547e3193eb61d694ff505f6706929f5aa628cda5/PANDORA/Database/Database.py#L223)
3) For the .csv files I will have to reply later, I do not remember and cannot check now, sorry.
4) If there are not too many files, I would not bother with another subfolder for those two fastas... Please let me know what you think it's better
5) first, should we change PANDORA_files to maybe PANDORA_database or just "Databases" or something similar? Isn't files too vague? Second, maybe it's better to keep the name "IMGT_retrieved" to mark that those are the files exactly as downloaded from IMGT, and not simply files that come from IMGT.
6) Yes, please, delete csv_pkl_files. There is no need for it anymore (and there hasn't been for a looooong time...)

**Comment by gcroci2** [comment]
> Hi Giulia:
> 
> 1. About the "Bad" folder: yes, it is better two keep two separate pMHCI and II folders inside for clarity reason.
> 2. For the blast database: called in [line 112 of Database.py](https://github.com/X-lab-3D/PANDORA/blob/547e3193eb61d694ff505f6706929f5aa628cda5/PANDORA/Database/Database.py#L112) (from the development branch), they are produced by [this function.](https://github.com/X-lab-3D/PANDORA/blob/547e3193eb61d694ff505f6706929f5aa628cda5/PANDORA/Database/Database.py#L223)
> 3. For the .csv files I will have to reply later, I do not remember and cannot check now, sorry.

TBD

> 4. If there are not too many files, I would not bother with another subfolder for those two fastas... Please let me know what you think it's better

The fasta files are the blast databases mentioned above, and there are only two files (Human_MHC_data.fasta and NonHuman_MHC_data.fasta). I'll keep them in default/ without creating a specific folder.

> 5. first, should we change PANDORA_files to maybe PANDORA_database or just "Databases" or something similar? Isn't files too vague? Second, maybe it's better to keep the name "IMGT_retrieved" to mark that those are the files exactly as downloaded from IMGT, and not simply files that come from IMGT.

Let's use "Databases" and "IMGT_retrieved".

> 6. Yes, please, delete csv_pkl_files. There is no need for it anymore (and there hasn't been for a looooong time...)

**Comment by gcroci2** [comment]
See PR #164 @DarioMarzella. I've run the tests locally and they pass, as well as the CI checks.  

- From the readme: _PANDORA needs a PDB template database to work (retrieved from [IMGT](http://www.imgt.org/3Dstructure-DB/) database). You can download it from https://github.com/X-lab-3D/PANDORA_database (pMHC I only, generated on 23/03/2021) and follow the [instructions](https://github.com/X-lab-3D/PANDORA_database/blob/main/README.md). Please be sure you re-path your database as explained in the instructions._ I've done it but I've got stuck because of muscle5, there is an issue about running it on my Mac for privacy reason and I should contact them. Could you verify that the folders are populated correctly in such case?
- From the readme: _Alternatively, you can generate your template database(suggested) with the following python3 code: [...]._ Here it's not clear what to do. If I try to run `db.construct_database(save='path/to/pandora_Database.pkl')` without having copied https://github.com/X-lab-3D/PANDORA_database, it gives me `FileNotFoundError: [Errno 2] No such file or directory: '.../PANDORA/Databases/default/PDBs/IMGT_retrieved/'`. So am I supposed to place in PANDORA the database folder also in this second case? If yes, it's not clear from the readme. And if yes, it seems that the code is looking for `IMGT_retrieved/` folder, that is not present in https://github.com/X-lab-3D/PANDORA_database, but from what I understood is generated by PANDORA during the process.
