### ISSUE TITLE
Failing with different number of jobs using wrapper for MHCII benchmarking

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#157]
### Expected Behavior:

Models all benchmark cases in .tsv file running wrapper

### Current Behavior:

For MHC II even for the first case (1AQD) when trying to model this error occurs,
For MHC I after modeling some cases this error occurs:

> [Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
> Traceback (most recent call last):
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Pandora.py", line 358, in model
>     self.align(verbose=verbose)
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Pandora.py", line 150, in align
>     self.alignment = Align.Align(self.target, self.template, output_dir=self.output_dir)
>   File "/mnt[/home1/fmeiman/PANDORA/PANDORA/Pandora/Align.py", line 69, in __init__
>     self.aligned_seqs_and_pept = self.__align_chains()
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Align.py", line 131, in __align_chains
>     aligned_pepts = self.__align_peptides()
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Align.py", line 203, in __align_peptides
>     longest_3nd_anch = max((v[1][2], k) for k, v in id_pept_anch.items())[0]
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Align.py", line 203, in <genexpr>
>     longest_3nd_anch = max((v[1][2], k) for k, v in id_pept_anch.items())[0]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "run_realanchor_benchmark.py", line 80, in <module>
>     wrap.run_pandora(num_cores=n_cores, n_loop_models=20,
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Wrapper/Wrapper.py", line 275, in run_pandora
>     Parallel(n_jobs = num_cores, verbose = 1)(delayed(run_model)(job) for job in list(self.jobs.values()))
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 1048, in __call__
>     if self.dispatch_one_batch(iterator):
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
>     self._dispatch(tasks)
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 784, in _dispatch
>     job = self._backend.apply_async(batch, callback=cb)
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
>     result = ImmediateResult(func)
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
>     self.results = batch()
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
>     return [func(*args, **kwargs)
>   File "/home/fmeiman/anaconda3/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
>     return [func(*args, **kwargs)  File "/mnt/home1/fmeiman/PANDORA/PANDORA/Wrapper/run_model.py", line 46, in run_model
>     mod.model(n_loop_models=n_loop_models, n_jobs=n_jobs,
>   File "/mnt/home1/fmeiman/PANDORA/PANDORA/Pandora/Pandora.py", line 361, in model
>     raise Exception('Failed aligning target and template')
> Exception: Failed aligning target and template

### Detailed Description:

Using Wrapper for MHCI and MHCII  this error occurs after finding the best template.
When trying to align template and target, to be used to superimpose the target on the template structure for later steps.

**Comment by DarioMarzella** [comment]
Hi Farzaneh, can you upload your script and the .tsv file you used, or at least one row of it? 
From the error, it would seem like the error is due to an anchor out of index...

**Comment by FarzanehParizi** [comment]
Hi Dario,
Thanks for the hint. It was super helpful. I checked there was indeed a typo in a row for the case with three anchors. Now it seems to be working.
