### ISSUE TITLE
 new version of muscle incompatible with biopython

### ISSUE THREAD

**Issue by v-mikhaylov** [X-lab-3D/PANDORA#159]
I followed the GitHub/Pypi installation. The line `conda install -c bioconda muscle` installs muscle version 5.1 which doesn't work with the output of `Bio.Align.Applications.MuscleCommandline`. The problem got fixed by reverting to muscle version 3.8.  Please change the instructions to `conda install -c bioconda muscle=3.8`

**Comment by DarioMarzella** [comment]
Hi @v-mikhaylov , thanks a lot for reporting this!
This is related to #138, [here](https://github.com/X-lab-3D/PANDORA/issues/138#issuecomment-1206497013).

**Comment by DarioMarzella** [comment]
It is fixed now in the README ( fe7e014 ). We will make sure muscle version issues are solved in the new release.

**Comment by v-mikhaylov** [comment]
Thank you!
