### ISSUE TITLE
Missing commas in the tutorial's Python code

### ISSUE THREAD

**Issue by Smaassen2** [X-lab-3D/PANDORA#168]
The master branch is missing one comma (after 'myTestCase') and the development branch is missing 2 commas (after 'myTestCase' and 'HLA-A*0201') in example 1 of the tutorial.

Master branch:

## B. Create Target object
target = PMHC.Target(id = 'myTestCase'
    allele_type = ['HLA-A*0201'],
    peptide = 'LLFGYPVYV',
    anchors = [2,9])

Development branch:

## B. Create Target object
target = PMHC.Target(id = 'myTestCase'
    allele_type = 'HLA-A*0201'
    peptide = 'LLFGYPVYV',
    anchors = [2,9])

**Comment by DarioMarzella** [comment]
Hi @Smaassen2 , thanks for pointing it out. I will fix the master README now, but the development will be updated with the next PR to avoid conflicts, as there are many pending branches.
