### ISSUE TITLE
hardcoded dependency paths

### ISSUE THREAD

**Issue by cbaakman** [X-lab-3D/PANDORA#172]
I tried to run pandora on a cluster, but the following file paths are hardcoded in pandora:
- muscle align executable
- modeler python module

I cannot install these software packages at their default location, since I have no root rights. It would be nice if these paths were configurable.

**Comment by DarioMarzella** [comment]
Hi @cbaakman , there is no hardcoded path for these packages. They are simply called by PANDORA, to work muscle should be defined in your path and modeller should be installed as python package.
The easiest way to have them working is to install everything (including PANDORA and these packages) through conda.

**Comment by cbaakman** [comment]
I will try conda, thanks!
