### ISSUE TITLE
how to allow the user to specify the path to the downloaded database

### ISSUE THREAD

**Issue by LilySnow** [X-lab-3D/PANDORA#174]
How to allow the user to specify the path to the downloaded database?

**Comment by DarioMarzella** [comment]
This is now properly working in v2.0.0-alpha. PANDORA has its own default database path that the user does not need to know or edit necessarily, but in case the user can add/edit a config.json file specifying the database folder name.
There is still no way to add a whole new path for the database, but it does not seem crucial at this point, as users are hardly likely to use many different databases.
