### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jcgrenier** [X-lab-3D/PANDORA#225]
Hello! We are working on a private cluster that does not permit us to work with Conda. 
Would that be feasible for you to generate a docker image so we can install it on this type of machine?

Thanks a lot!

Jean-Christophe

**Comment by DarioMarzella** [comment]
Hello Jean-Christophe, thanks for reaching out!

Yes, it is possible to get a docker container but we did not start setting up one yet. We will look into it but it could take us a few days.

In the meantime, although I never tested it I am quite sure you can install PANDORA without conda, as long as your system allows you to use `pip install`.
To do so, you should: 
1) install modeller and muscle from source (do not use the pypi version of muscle, it's quite outdated. Also, we are adding command-line tools soon in the development.)
2) clone the PANDORA repo (and I strongly recommend to switch to the development branch. It has serious improvements from the master version.)
3) move to the PANDORA folder andinstall with `pip install -e ./`

In case you need an help with the conda-less installation or encounter any issue I will be happy to help.
I will post here updates reguarding the docker container as soon as possible.

**Comment by DarioMarzella** [comment]
Also, I just thought about it: maybe it's a naive question, but did you try to use miniconda instead?
In general you do not need admin permission to install anaconda or miniconda, you can just install it in your home folder. We also work on clusters where we have no admin rights and we use conda regularly. 
How did you try to install it, if I may ask?

**Comment by jcgrenier** [comment]
Hello @DarioMarzella ,
I did try through a python virtual environment so far, but got issues with some dependencies versions that I was not able to get installed on our system. I'll try again with what you proposed and keep you posted! 

Thanks a lot for your help!

**Comment by DarioMarzella** [comment]
No problem!
Try downloading it from here https://www.anaconda.com/products/distribution and install it following their guide.

Also, the first conda release of PANDORA has some issues on the installation side. I will try to do at least a pre-release of the new version soon, hopefully today, so you can install that one instead.

**Comment by jcgrenier** [comment]
Awesome! I'll wait for this version then!

**Comment by DarioMarzella** [comment]
Hi @jcgrenier , the new conda (pre-)release is available now.
Once you have your anaconda or miniconda set up, you can install PANDORA by following the instructions here: https://github.com/X-lab-3D/PANDORA/blob/development/README.md

**Comment by jcgrenier** [comment]
Thank you very much! I'll keep you posted if I run into any trouble!

**Comment by DarioMarzella** [comment]
Thank you! I hope it is helpful!
In case the conda installation turns out to not be an option, we can proceed with a Docker container. We were going to create one anyways, so we can just test it out for you :)

**Comment by jcgrenier** [comment]
Hello @DarioMarzella ,
Finally the admin on our cluster don't want us to use any *conda system. If you could provide us a container, it would really be awesome!

Thanks a lot!

**Comment by DarioMarzella** [comment]
I see, very unfortunate.
We will provide you with a docker container as soon as possible then.
________________________________

**Comment by jcgrenier** [comment]
Hello @DarioMarzella , that's a pretty good point. 
We do not have access to Docker, but Singularity on our cluster. I'm usually able to convert Docker images to Singularity ones. But I would need to build the Docker image from my laptop before transferring it on the cluster. So I guess it will work anyway. 

Thanks a lot!

**Comment by DarioMarzella** [comment]
Hi @jcgrenier , I managed to make the docker recipe and test it. 
You can find the instructions in the readme of the development branch: https://github.com/X-lab-3D/PANDORA/tree/development#docker

If you encounter any issue, please let me know. As I mentioned earlier, we are not allowed to release third parties software or software licenses, but I hope I provided a good explanation on how to have everything running.

Let me know how it goes!

**Comment by jcgrenier** [comment]
That's awesome! Thanks a lot for doing it so quickly! We will let you know how the installation goes!

**Comment by jcgrenier** [comment]
Hello @DarioMarzella , we succeeded installing the software! We even transferred it to a singularity image file successfully afterwards! Thanks a lot again for all that help!
