### ISSUE TITLE
Neoantigens from SNV

### ISSUE THREAD

**Issue by GuidoLeoni** [X-lab-3D/PANDORA#229]
Dear developers of Pandora
Do you have any tips about modeling MHC-I 9mers  of mut/wt peptides derived from Single nucleotide variants?
  

I have the following case of study 
mut peptide:CVRVSGQGL (validated immunogenic neoantigen therefore it is surely bound by MHC)
wt peptide:RVRVSGQGL (predicted binder with an IC50 of 24nM)
I believed that for this special case the mut and wt counterpart would have a quite similar modeled structure
Instead after modeling both peptides with PANDORA i noticed that the models are quite different.
In particular PANDORA uses  2 different templates (4U1K for wt; 41US for mut). The 2 pdbs have the same MHC and differ only for the 9mer bound into the pocket. 
I guess that  4U1K has been preferred as template for the mut peptide because its 9mer peptide starts with Arg.

Is there a way to force the modeling of mut peptide by using exactly the same pdb used for wt?
thank you for any tip
Guido

**Comment by DarioMarzella** [comment]
Dear @GuidoLeoni, first of all, thanks a lot for using our software and contacting us!

For sure you can force pandora to use a template selected by you. 
If you are using PANDORA's Python interface, you have to retrieve the template from the template database and pass it to the Pandora object, as shown in the example below:

`from PANDORA import Target, Template, Database

db = Database.load()
target = Target(id = MyMutCase', #or whatever ID you prefer
    allele_type = 'HLA-A*0201', # or whatever MHC allele you are using
    peptide = 'RVRVSGQGL,
)

# Selece a template from the template database using its PDB ID
template = db.MHCI_data['4U1K']
# Pass the template to the modelling function
case = Pandora.Pandora(target, db,  template=[template])
case.model()
`

Also, please make sure you select the lowest molpdf model generated from each run (by checking the output file molpdf_DOPE.tsv. Indeed, considering how similar the sequences are and that the mutation is before the first anchor (unless you think the anchor positions are different for some reason), the lowest energy structures should look very similar to each other. 

Unfortunately, the manual template selection has not been implemented yet for the command line interface of PANDORA. If you are using our package from the command line, please let me know and I can add this feature for the next pre-release.

Please let me know if you have any further questions!
