### ISSUE TITLE
Blast version 

### ISSUE THREAD

**Issue by bsb2014** [X-lab-3D/PANDORA#250]
I got an error when installing pandora using Conda, 

Could not solve for environment specs
Encountered problems while solving:
  - package csb-pandora-2.0.0beta2-py311_0 requires blast 2.10.*, but none of the providers can be installed.

Does the latest blast (2.14.1) work with pandora-2.0?

Thanks

**Comment by DarioMarzella** [comment]
Hi @bsb2014, thanks for reporting this!
Could you please paste here the command that you run exactly, plus the full error log? It looks like the correct version of blast cannot be found, but I just tested it and it's still available, so I guess something else must have gone wrong.

As of your question, we haven't tested blast 2.14 yet, but in theory being the same major version of blast, it should work just fine. The only issue might be for the PANDORA database that you can download with ```pandora-fetch```. If the blast versions don't correspond than the blast database might not be readable, so you'll have to regenerate it yourself (https://csb-pandora.readthedocs.io/en/latest/tutorial.html#download-template-database ).

**Comment by bsb2014** [comment]
Thanks for your response. 

The command is: 

mamba  install -c csb-nijmegen csb-pandora=2.0.0beta2 -c salilab -c bioconda

The log is: 

Looking for: ['csb-pandora=2.0.0beta2']

warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
warning  libmamba Could not parse mod/etag header
csb-nijmegen/linux-64                                         No change
salilab/noarch                                                No change
csb-nijmegen/noarch                                           No change
salilab/linux-64                                              No change
pkgs/main/noarch                                   853.2kB @ 908.3kB/s  0.5s
pkgs/r/linux-64                                      1.7MB @   1.3MB/s  0.9s
pkgs/r/noarch                                        2.0MB @   1.2MB/s  0.8s
bioconda/linux-64                                    5.2MB @   2.7MB/s  2.2s
bioconda/noarch                                      4.7MB @   1.9MB/s  2.2s
pkgs/main/linux-64                                   6.2MB @   2.0MB/s  2.7s

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
Encountered problems while solving:
  - package csb-pandora-2.0.0beta2-py311_0 requires blast 2.10.*, but none of the providers can be installed

The environment can't be solved, aborting the operation.


In environment.yml (https://github.com/X-lab-3D/PANDORA/blob/master/environment.yml), blast =2.10 was defined. Does that possibly cause the problem?

Thanks

**Comment by bsb2014** [comment]
By the way, I can not install blast 2.10.* on my machine due to Perl incompatibility. My blast is 2.14.1 (the latest version)

**Comment by DarioMarzella** [comment]
I see. I am very sorry for this inconvenience.
Indeed, if you cannot install blast 2.10 because of Perl incompatibility, I would expect the installation to crash... I would just not expect this error message.
Are you trying this installation in your base environment or in a clean new environment?

Anyways, I will test blast 2.14 and let you know, I am very sorry for the inconvenience.
Meanwhile, you can try the pip installation ( https://github.com/X-lab-3D/PANDORA#github--pypi-installation ), but installing blast 2.14 and remove the blast version requirement from the environment before runnin ```pip install -e ./```.

**Comment by DarioMarzella** [comment]
It looks like installing blast 2.14.1 on the systems I use it's also very hard, due to multiple dependencies. It will take me more than expected to test it on my side.
Can you please try the solution I suggested, by using the pip installation, removing the blast requirement and running PANDORA with blast 2.14.1?

**Comment by bsb2014** [comment]
I will try the solution today and let you know the results.

**Comment by bsb2014** [comment]
The installation was smooth and no error popped up. pandora-fetch was used to download the database (Checking...
Database correctly retrieved).

then I tested PANDORA without any inputs

pandora-run

usage: PANDORA [-h] -a ALLELE [-c] [-i ID] [-k ANCHORS] [-l LOOP_MODELS] -m {I,II} [-o OUTPUT_PATH] -p PEPTIDE [-N] [-r RESTRAINTS_STDEV]
PANDORA: error: the following arguments are required: -a/--allele, -m/--mhc-class, -p/--peptide

tested PANDORA with inputs

pandora-run -m I -i myTestCase -a HLA-A*0201 -p LLFGYPVYV -k 2,9

Got an error

FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/PANDORA_databases/default/PANDORA_database.pkl'

I am wondering where should I store the template database. I did not find the PANDORA_databases folder after fetching.

Thanks

**Comment by bsb2014** [comment]
Which argument should be used if MHC protein seq is provided? Thanks

**Comment by DarioMarzella** [comment]
> I am wondering where should I store the template database. I did not find the PANDORA_databases folder after fetching.
That is weird. ```pandora-fetch``` should create the folder `/home/xxx/PANDORA_databases/default/` and place in there the relative files... Or should at least raise an error if something goes wrong. May I ask what is your operative system?

> Which argument should be used if MHC protein seq is provided? Thanks 
You have to provide peptide, mhc class, allele name and MHC sequence. As of now, the allele name is just redundant if you provide the MHC sequence, but still needs to be given. I will remove it from the required arguments with the next update.

**Comment by bsb2014** [comment]
My fault, I found the PANDORA_databases. The folders mhcseqs and BLAST_databases are empty, and there is no PANDORA_database.pkl file under PANDORA_databases.


For example, I ONLY have MHCII DRB1 fasta (no allele name) and peptide fasta. How to use PANDORA to build the docking?
 
Thanks

**Comment by DarioMarzella** [comment]
Those folder are not supposed to be empty after running ```pandora-fetch```.
Can you try running this in python, anche then checking if your PANDORA_databases folder has the necessary files?

`from PANDORA import Database

Database.install_database()`

To model your case (pandora performs an integrative modeling, not exactly a docking) if you only have the sequence, the best way it is in python. The command line implementation is more for very quick runs where all the basic information are available.

`## import requested modules
from PANDORA import Target
from PANDORA import Pandora
from PANDORA import Database

## A. Load local Database
db = Database.load()

## B. Create Target object
target = Target(id = 'myTestCase',
    N_chain_seq= <YourDRB1Sequence>, 
    peptide = <YourPeptide>, # example: 'ALESEKLKLFRA'
    anchors = <ExpectedAnchors>, #example: [2,5,7,9]
    MHC_class='II')

## C. Perform modelling
case = Pandora.Pandora(target, db)
case.model()`

Make sure you fill in <YourDRB1Sequence>, <YourPeptide> and <ExpectedAnchors>. If you don't know the anchors for your peptide, you should install NetMHCIIpan (see info here https://github.com/X-lab-3D/PANDORA#optional-install-netmhcpan-andor-netmhciipan ), then you can add the argument "use_netmhcpan=True" to the Target class.

**Comment by bsb2014** [comment]
Thanks for your detailed reply. How does Pandora look for netMHCpan II? Do I need to provide a absolute path?

**Comment by DarioMarzella** [comment]
PANDORA will assume netmhcpan is in the PATH, reachable by command line by simply calling "netmhcpan" (or netmhciipan). Also adding an alias for it should work.

No, you don't need to specify between netmhcpan and netmhciipan: PANDORA will decide which predictor to use based on the MHC class of your target, so simply make sure you specify `MHC_class = 'I'` in your Target

**Comment by bsb2014** [comment]
Hi, the folders mhcseqs and BLAST_databases are still empty. Please look at the log below 


Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PANDORA import Database
>>> Database.install_database()
Downloading pre-built database from zenodo...
--2023-11-02 09:20:09--  https://sandbox.zenodo.org/record/1163695/files/default.tar.gz?download=1
Resolving sandbox.zenodo.org (sandbox.zenodo.org)... 188.185.10.243, 188.185.35.172, 188.185.22.9, ...
Connecting to sandbox.zenodo.org (sandbox.zenodo.org)|188.185.10.243|:443... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: /records/1163695/files/default.tar.gz [following]
--2023-11-02 09:20:10--  https://sandbox.zenodo.org/records/1163695/files/default.tar.gz
Reusing existing connection to sandbox.zenodo.org:443.
HTTP request sent, awaiting response... 500 INTERNAL SERVER ERROR
2023-11-02 09:20:10 ERROR 500: INTERNAL SERVER ERROR.

Copying the database

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Checking...
Database correctly retrieved
>>> exit()

**Comment by DarioMarzella** [comment]
I see what happened here, thanks for reporting it. I need to update the zenodo link.
Give me a few minutes, and I will do the new zenodo release.

I will reply here with the instructions on how to get the database. Sorry for the inconvenience.

**Comment by DarioMarzella** [comment]
Done, you can now download the database. In order to do it without changing your PANDORA installation, you will need to run the following script:

```
from PANDORA import Database

db = Database.Database()

#Download the templates database
db.fetch_database(db_out_path='~/PANDORA_databases/default,
    db_url='https://zenodo.org/records/7318263/files/default.tar.gz?download=1')
#Rebuild the blast databases to make sure they are compatible with the blast version installed
db.construct_both_blast_db()
```

This will take care of both downloading the database and the associated files, and regenerating the blast databases with your blast installation, so you can be sure they are compatible with it.

Let me know if it works!

**Comment by bsb2014** [comment]
Another error

>>> db.fetch_database(db_out_path='~/PANDORA_databases/default',db_url='https://zenodo.org/records/7318263/files/default.tar.gz?download=1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Database' object has no attribute 'fetch_database'

**Comment by DarioMarzella** [comment]
Oh, my bad, sorry. This should work, just tested it:

```
from PANDORA import Database

#Download the templates database
Database.fetch_database(db_out_path='~/PANDORA_databases/default',
    db_url='https://zenodo.org/records/7318263/files/default.tar.gz?download=1')

db = Database.load()
#Rebuild the blast databases to make sure they are compatible with the blast version installed
db.construct_both_blast_db()
```

**Comment by bsb2014** [comment]
It did not work and I did not find the folder PANDORA_databases at /home/xxxx/

>>> Database.fetch_database(db_out_path='~/PANDORA_databases/default',db_url='https://zenodo.org/records/7318263/files/default.tar.gz?download=1')
Downloading pre-built database from zenodo...
/home/xxxx/PANDORA_databases/default.tar.gz: No such file or directory
Copying the database
tar (child): /home/xxxx/PANDORA_databases/default.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: cannot remove '/home/xxx/PANDORA_databases/default.tar.gz': No such file or directory
Checking...
Database correctly retrieved
>>> exit()

**Comment by DarioMarzella** [comment]
Can you please first make the folder `/home/xxxx/PANDORA_databases` and then run the script again?

**Comment by bsb2014** [comment]
This time, folders mhcseqs and BLAST_databases looks fine, but PANDORA_database.pkl is not there.

>>> Database.fetch_database(db_out_path='~/PANDORA_databases/default',db_url='https://zenodo.org/records/7318263/files/default.tar.gz?download=1')
Downloading pre-built database from zenodo...
--2023-11-02 10:36:16--  https://zenodo.org/records/7318263/files/default.tar.gz?download=1
Resolving zenodo.org (zenodo.org)... 188.185.22.33, 188.185.10.78, 188.185.33.206, ...
Connecting to zenodo.org (zenodo.org)|188.185.22.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 79429632 (76M) [application/octet-stream]
Saving to: ‘/home/xxxx/PANDORA_databases/default.tar.gz’

/home/xxxx/PANDORA_databases/default.ta 100%[============================================================================>]  75.75M  14.4MB/s    in 7.3s

2023-11-02 10:36:24 (10.3 MB/s) - ‘/home/xxxx/PANDORA_databases/default.tar.gz’ saved [79429632/79429632]

Copying the database

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Checking...
Database correctly retrieved
>>> db = Database.load()
Traceback (most recent call last):
  File "/mnt/chsrhome/xxxx/src/PANDORA/PANDORA/Database/Database.py", line 304, in load
    with open(file_name, 'rb') as inpkl:
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/PANDORA_databases/default/PANDORA_database.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/chsrhome/xxxx/src/PANDORA/PANDORA/Database/Database.py", line 308, in load
    raise Exception('Database file not found. Are you sure you have it? If not, run Database.construct_database()')
Exception: Database file not found. Are you sure you have it? If not, run Database.construct_database()
>>> exit()

**Comment by bsb2014** [comment]
Do I need to download the database to the PANDORA installation folder?

**Comment by DarioMarzella** [comment]
> Do I need to download the database to the PANDORA installation folder?
No, there is no need for. It should go automatically to your home folder.

It looks like there is an issue with the database file I uploaded. Let me run some tests and try to fix it.

**Comment by DarioMarzella** [comment]
In the meantime you can actually just generate the database yourself. it's probably the cleanest and safest option. here are some info: https://csb-pandora.readthedocs.io/en/latest/tutorial.html#download-template-database

The python script is very simple:
`## import requested modules
from PANDORA import Database

## A. Create local Database
db = Database.Database()
db.construct_database(n_jobs=<n_jobs>)`

Remember to change <n_jobs> with the number of CPU cores your script is allowed to use. I advice to use at least 8 if possible, and generating the database shouldn't take more than 20~30 minutes.

**Comment by DarioMarzella** [comment]
I see. This is indeed another issue that I will solve asap ( https://github.com/X-lab-3D/PANDORA/issues/252 ). Sorry for the inconvenience. What I don't understand is why you don't have those folders, as they should have been generated as first thing when you run the code to download the database. Did you by any chance wiped the PANDORA_databases folder to have a clean installation?

Anyways, you can use the following code to generate the appropriate folders and create your database:

```
## import requested modules
from PANDORA import PANDORA_data
from PANDORA import Database

## Create the folders
Database.create_db_folders(db_path=PANDORA_data)

##  Create local Database
db = Database.Database()
db.construct_database(n_jobs=<n_jobs>)

```
as before, remember to change <n_jobs>.

**Comment by bsb2014** [comment]
It is working now and creating the database. After that, I will test the PANDORA and keep you posted. Thanks for your help.

**Comment by bsb2014** [comment]
Just tested pandora-run -m I -i myTestCase -a HLA-A*0201 -p LLFGYPVYV -k 2,9. It worked well. 

I  understand that the pandora can work with 15-aa peptide (MHCII). Can it work with the full-length peptide?  Thanks

**Comment by DarioMarzella** [comment]
Great! Happy to hear it's working now.
Sorry, I am not really sure I understand your question. What do you mean with "the full-length peptide"? 
A 15-aa peptide? In that case, yes.
A longer peptide? Yes, but I believe the longest we tested was a 23-aa peptide. 
Did you mean a full-length protein, asking if PANDORA also takes care of the processing into shorter peptides? In that case, no, it's not between PANDORA's functions.

**Comment by bsb2014** [comment]
You answered my question. Thanks.
