### ISSUE TITLE
User-defined MHC sequence

### ISSUE THREAD

**Issue by bsb2014** [X-lab-3D/PANDORA#253]
I put the codes below in the PANDORA.py 

from PANDORA import Target
from PANDORA import Pandora
from PANDORA import Database
db = Database.load()
target = Target(id = 'ara1',
    N_chain_seq= 'xxxxxxxxxxx',
    peptide = 'xxxxxxxxxxxx', 
    use_netmhcpan = True,
    MHC_class='II')
case = Pandora.Pandora(target, db)
case.model()

and then python ./PANDORA.py but got an error 

Traceback (most recent call last):
  File "/mnt/chsrhome/xxxx/./PANDORA.py", line 2, in <module>
    from PANDORA import Target
  File "/mnt/chsrhome/xxxx/PANDORA.py", line 2, in <module>
    from PANDORA import Target
ImportError: cannot import name 'Target' from partially initialized module 'PANDORA' (most likely due to a circular import) (/mnt/chsrhome/xxxx/PANDORA.py)

Just tested pandora-run -m I -i myTestCase -a HLA-A*0201 -p LLFGYPVYV -k 2,9. It worked well. However, the command line seems not to have the argument for "N_chain_seq".

**Comment by DarioMarzella** [comment]
Hi @bsb2014, that is not exacty how PANDORA is supposed to be used (nor most part of other python packages installed from source).

You are not supposed to change the package itself in any way, nor you need your scripts to be in the same folder. Once you have run the installation (in your case, according to issue #250 , `pip install e .`), PANDORA will be available as a python package to any python (py3) scripts that runs in that same environment (in your case, I assume the conda environment set up by mamba).

So, you can create your python script (e.g. MyScript.py), and put your code in there:

```
from PANDORA import Target
from PANDORA import Pandora
from PANDORA import Database
db = Database.load()
target = Target(id = 'ara1',
N_chain_seq= 'xxxxxxxxxxx',
peptide = 'xxxxxxxxxxxx',
use_netmhcpan = True,
MHC_class='II')
case = Pandora.Pandora(target, db)
case.model()
```

This will import PANDORA, even if it's not in the same folder or script. 
Please remember to change back all the edits you made to PANDORA.py. That, and all the other files from the package, should stay unchanged.

On the other hand, the command-line implementation (" pandora-run -m I -i myTestCase -a HLA-A*0201 -p LLFGYPVYV -k 2,9 " ) it's designed to quickly model straightforward cases, therefore is much more flexible and open to personalization than the python interface.

Please let me know if you have any further questions!

**Comment by bsb2014** [comment]
This time, I put the codes in PANDORA_MHCii.py and got a different error as follows

WARNING: Missing M chain (Alpha chain) sequence and allele name.
Traceback (most recent call last):
  File "/mnt/chsrhome/xxxx/./PANDORA_MHCii.py", line 10, in <module>
    target = Target(id = 'ara1',
  File "/mnt/chsrhome/xxxx/src/PANDORA/PANDORA/PMHC/PMHC.py", line 300, in __init__
    self.fill_allele_seq_info(use_templ_seq=use_templ_seq)
  File "/mnt/chsrhome/xxxx/src/PANDORA/PANDORA/PMHC/PMHC.py", line 538, in fill_allele_seq_info
    raise Exception('No MHC chain available')
Exception: No MHC chain available

I would appreciate if if you could give me some suggestions.

**Comment by DarioMarzella** [comment]
I see. To model MHC-II cases, PANDORA needs informations about both the MHC chains, or at leats it needs to know that your beta chain is HLA-DRB1, so it can automatically use HLA-DRA*01:01 as default alpha chain. 
So you can either specify both the chains allele names (the beta chain allele name won't be used to replace your user-defined N_chain_seq, no need to worry about that), or specify only the beta chain name and let pandora automatically assign the alpha chain, or give a sequence for the both of them:

#### Specify both allele names:
```
from PANDORA import Target
from PANDORA import Pandora
from PANDORA import Database
db = Database.load()
target = Target(id = 'ara1',
allele_type=['HLA-DRB1*01:01', 'HLA-DRA*01:01']
N_chain_seq= 'xxxxxxxxxxx',
peptide = 'xxxxxxxxxxxx',
use_netmhcpan = True,
MHC_class='II')
case = Pandora.Pandora(target, db)
case.model()
```

#### Or specify the Alpha chain sequence as M_chain_seq (I used the HLA-DRA*01:01 that you can also find in your database at `~/PANDORA_databases/default/mhcseqs/HLA_cleaned.fasta`)
```
from PANDORA import Target
from PANDORA import Pandora
from PANDORA import Database
db = Database.load()
target = Target(id = 'ara1',
M_chain_seq='MAISGVPVLGFFIIAVLMSAQESWAIKEEHVIIQAEFYLNPDQSGEFMFDFDGDEIFHVDMAKKETVWRLEEFGRFASFEAQGALANIAVDKANLEIMTKRSNYTPITNVPPEVTVLTNSPVELREPNVLICFIDKFTPPVVNVTWLRNGKPVTTGVSETVFLPREDHLFRKFHYLPFLPSTEDVYDCRVEHWGLDEPLLKHWEFDAPSPLPETTENVVCALGLTVGLVGIIIGTIFIIKGVRKSNAAERRGPL'
N_chain_seq= 'xxxxxxxxxxx',
peptide = 'xxxxxxxxxxxx',
use_netmhcpan = True,
MHC_class='II')
case = Pandora.Pandora(target, db)
case.model()
```

Let me know if it works!

**Comment by DarioMarzella** [comment]
Great, all looks good! Remember now that `ara1.BL00190001.pdb` is the best model, but you can also take a look at the other top-5 models, as their molpdf score seems to be quite similar. 
Good luck with your project!

**Comment by bsb2014** [comment]
Many thanks for your help with setting up the Pandora!!

**Comment by bsb2014** [comment]
Is it normal if Molpdf score is negative? thanks

**Comment by DarioMarzella** [comment]
Hi, yes. Molpdf is the MODELLER objective function, it's a relative score and it can easily be negative. The lower it is, the better the model, but it can be used only to compare between models of the same complex (i.e. you cannot use it to compare between models of different peptide-MHC complexes)
