### ISSUE TITLE
conda installation fails

### ISSUE THREAD

**Issue by LilySnow** [X-lab-3D/PANDORA#260]
![image](https://github.com/user-attachments/assets/2a80754d-85f5-4293-a103-c0a1c13b045f)

Github installation is fine. But with conda, we can automatically install dependencies...

For the database, `pandora-fetch` does not work properly, as zenodo is missing a file (see issue #258). We can use `pandora-create -c <num_cores>`, for example, `pandora-create -c 4` to build the database ourselves.

**Comment by LilySnow** [comment]
Once installed PANDORA with conda, the package is there correctly installed, but for some reason it does not appear in the environment, so it cannot be directly imported.

**Comment by gcroci2** [comment]
I confirm that the PANDORA import in Python fails, even though the installation doesn't throw any error. PANDORA is not in the conda list of packages.

About the Python version, as I mentioned above, the Conda package metadata should specify correct Python versions _range_, so that users do not need to worry about having a too new python version by default. 

> @gcroci2 one environment can host packages from multiple python versions. Can you test if we can solve this issue by simply specifying the python version in the PANDORA install command line, rather than having to make an environment with a specific version?

Yes, you can do `conda install package_name python=3.11`

**Comment by DarioMarzella** [comment]
Ok good, so it should be solved by simply changing the python version range in the environment.yml. I can take care of that.


> I confirm that the PANDORA import in Python fails, even though the installation doesn't throw any error. PANDORA is not in the conda list of packages.

Just for curiosity, can you check your ```~/miniconda3/envs/<yourenv>/lib/python3.12/site-packages/PANDORA```? For me, PANDORA was there, but it would not show up 
in the package list

**Comment by gcroci2** [comment]
> Just for curiosity, can you check your `~/miniconda3/envs/<yourenv>/lib/python3.12/site-packages/PANDORA`? For me, PANDORA was there, but it would not show up in the package list

As I commented above, it is there indeed, but having installed python 3.11 in my environment it can't be found by python itself. And installation fails with python 3.12 (see my first comment).

**Comment by DarioMarzella** [comment]
This issue is unclear. I will open another one isolating the actual problem.
