### ISSUE TITLE
During database building, if runned on cluster, the temporary path is saved in the template objects.

### ISSUE THREAD

**Issue by DarioMarzella** [X-lab-3D/PANDORA#86]
During database building, if runned as a queued job on a cluster, the temporary path (es. "/mnt/home/UserName") is saved in the template objects as template.pdb_path.
This leads PANDORA to crash in case it is then runned from command line.

**Comment by DarioMarzella** [comment]
Related to #142

**Comment by LilySnow** [comment]
Can be solved by assuming that the .pkl file is always in the same folder as the rest of the db and using relative paths.

**Comment by DarioMarzella** [comment]
Now that the Database folder is more stable and not changed by the user in the development branch, it can be solved by not using a path saved in the templates object but assigning dynamically with PANDORA.PANDORA_data + MHC class + template id

**Comment by DarioMarzella** [comment]
Fixed in #179
