### ISSUE TITLE
Changing the default Directory to which the Database to be Downloaded

### ISSUE THREAD

**Issue by FarzanehParizi** [X-lab-3D/PANDORA#93]
`Expected Behavior`:
By default saves the database in */PANDORA_files/data/csv_pkl_files/* Directory

`Current Behavior`:
saves the database in */PANDORA* Directory

`Detailed Description`:
The generated Database is a data type which is better not be downloaded in *./PANDORA* Directory which is for source codes.

**Comment by FarzanehParizi** [comment]
>
> from PANDORA.PMHC import PMHC
> from PANDORA.Pandora import Pandora
> from PANDORA.Database import Database
> 
>
> db = Database.Database()
> db.construct_database(save='pandora_Database.pkl')
> 
> target = PMHC.Target(
>     allele_ty:pe='HLA-A*0201'
>     peptide='LLFGYPVYV',
>     anchors = [2,9])
> 
>
> case = Pandora.Pandora(target, db)
> case.model()

**Comment by DarioMarzella** [comment]
the "save" argument in construct_database takes as input a file path. If you provide only "'pandora_Database.pkl" it will be saved as "./'pandora_Database.pkl", in your working directory. 
The PANDORA.PANDORA_data argument is used for this reason to point to your data folder.

**Comment by FarzanehParizi** [comment]
By `'pandora_Database.pkl`  as input, It saves to `'./PANDORA/Pandora_Database.pkl'` not to the main directory.
But I expect to be saved by default in `PANDORA_files/data/csv_pkl_files/` Directory.

**Comment by DarioMarzella** [comment]
What is your working directory?
Can you print it out with `os.getcwd()`?
